version: "3.9"

services:
  server:
    container_name: "log_injestor_server"
    image: "log_injestor_server"
    build:
      context: .
      target: ${TARGET}
    environment:
      - COMPOSE_PROJECT_NAME=${PROJECT_NAME}
    ports:
      - ${SERVER_PORT}:8000
    volumes:
      - .:/app
    depends_on:
      - postgresdb
      - mongodb

  postgresdb:
    container_name: "log_injestor_pg_db"
    image: "postgres:14-alpine"
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data

  mongodb:
    container_name: "log_injestor_mg_db" 
    image: "mongo"
    ports:
      - ${MONGO_PORT}:27017
    env_file:
      - .env
    volumes:
      - ${MONGO_DATA}:/var/lib/mongo/data

networks:
  default:
    name: ${PROJECT_NAME}_network
    external: true
